"""Migración inicial basada en modelos existentes

Revision ID: 4f4262907960
Revises: 
Create Date: 2025-04-01 17:39:55.682850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f4262907960'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('file_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('reflexion_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('interaction_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('interaction_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('idx_16505_sqlite_autoindex_password_reset_1')
        batch_op.create_unique_constraint(None, ['token'])

    with op.batch_alter_table('reflexion', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('titulo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('contenido',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('categoria',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('imagen',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('activation_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('subscription_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('preferred_categories',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True,
               existing_server_default=sa.text("'all'::text"))
        batch_op.alter_column('frequency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'weekly'::text"))
        batch_op.alter_column('birth_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.drop_index('idx_16515_sqlite_autoindex_user_1')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('onesignal_player_id')
        batch_op.drop_column('push_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('onesignal_player_id', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('idx_16515_sqlite_autoindex_user_1', ['email'], unique=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('frequency',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'weekly'::text"))
        batch_op.alter_column('preferred_categories',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'all'::text"))
        batch_op.alter_column('subscription_date',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('activation_token',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('reflexion', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('categoria',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('contenido',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('idx_16505_sqlite_autoindex_password_reset_1', ['token'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('token',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('interaction_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('interaction_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('reflexion_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('file_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
